```
└── 📁AppChat
    └── 📁AppChat
        └── 📁Controllers
            ├── AuthController.cs
            ├── ChatController.cs
            ├── ContactController.cs
            ├── MessageController.cs
            ├── UserController.cs
        └── 📁Data
            ├── AppDbContext.cs
        └── 📁Hubs
            ├── ChatHub.cs
        └── 📁Models
            └── 📁DTOs
                ├── LoginDTO.cs
                ├── MessageDto.cs
                ├── RegisterDTO.cs
                ├── SendMessageDTO.cs
            ├── Chat.cs
            ├── Contact.cs
            ├── Message.cs
            ├── User.cs
        └── 📁Properties
            ├── launchSettings.json
        └── 📁Repository
            ├── ChatRepository.cs
            ├── ContactRepository.cs
            ├── IChatRepository.cs
            ├── IContactRepository.cs
            ├── IMessageRepository.cs
            ├── IUserRepository.cs
            ├── MessageRepository.cs
            ├── UserRepository.cs
        └── 📁Services
            ├── ChatService.cs
            ├── ContactService.cs
            ├── MessageService.cs
            ├── TokenService.cs
            ├── UserService.cs
        └── 📁Utils
            ├── ConnectionHelper.cs
            ├── TimeHelper.cs
        └── 📁wwwroot
            └── 📁uploads
                ├── .gitkeep
        ├── AppChat.csproj
        ├── AppChat.http
        ├── AppChat.sln
        ├── appsettings.json
        ├── Program.cs
        ├── README.md
    ├── .dockerignore
    ├── .gitignore
    ├── AppChat.sln
    ├── docker-compose.yml
    └── Dockerfile
```